import {Weight} from "../../../shared/domain/model/weight.js";
import {WasteRecordId} from "./waste-record-id.js";
import {ProductionRecordId} from "./production-record-id.js";
import {Percentage} from "./percentage.js";

/**
 * Aggregate Root for the waste (merma) generated by one production process (US-14).
 * When the processed weight of that process is known, the waste percentage is calculated from it.
 */
export class WasteRecord {
    #id;
    #productionRecordId;
    #quantity;
    #baseWeight;
    #percentage;
    #recordedAt;

    /**
     * @param {{id?: WasteRecordId|null, productionRecordId: ProductionRecordId, quantity: Weight,
     *          baseWeight?: Weight|null, recordedAt: Date}} props
     *        baseWeight is the weight processed by the production record.
     */
    constructor({id = null, productionRecordId, quantity, baseWeight = null, recordedAt}) {
        if (id !== null && !(id instanceof WasteRecordId)) throw new Error('Invalid waste record id.');
        if (!(productionRecordId instanceof ProductionRecordId)) throw new Error('A waste record requires its production record.');
        if (!(quantity instanceof Weight) || !quantity.isPositive()) throw new Error('Waste quantity must be greater than zero.');
        if (baseWeight !== null && (!(baseWeight instanceof Weight) || !baseWeight.isPositive())) {
            throw new Error('The processed weight used as base must be greater than zero.');
        }
        if (baseWeight !== null && quantity.exceeds(baseWeight)) throw new Error('Waste cannot exceed the processed weight.');
        if (!(recordedAt instanceof Date) || Number.isNaN(recordedAt.getTime())) throw new Error('A waste record requires a valid date.');
        this.#id = id;
        this.#productionRecordId = productionRecordId;
        this.#quantity = quantity;
        this.#baseWeight = baseWeight;
        this.#recordedAt = new Date(recordedAt.getTime());
        this.#percentage = this.calculatePercentage();
    }

    /**
     * @param {{productionRecordId: ProductionRecordId, quantity: Weight, baseWeight?: Weight|null, recordedAt: Date}} props
     * @returns {WasteRecord}
     */
    static record({productionRecordId, quantity, baseWeight = null, recordedAt}) {
        return new WasteRecord({id: null, productionRecordId, quantity, baseWeight, recordedAt});
    }

    get id() {
        return this.#id;
    }

    get productionRecordId() {
        return this.#productionRecordId;
    }

    get quantity() {
        return this.#quantity;
    }

    get baseWeight() {
        return this.#baseWeight;
    }

    /** @returns {Percentage|null} null when there is no processed weight to compare with. */
    get percentage() {
        return this.#percentage;
    }

    get recordedAt() {
        return new Date(this.#recordedAt.getTime());
    }

    /** @returns {Percentage|null} */
    calculatePercentage() {
        if (this.#baseWeight === null) return null;
        const percentage = (this.#quantity.toKilograms() / this.#baseWeight.toKilograms()) * 100;
        return new Percentage(Math.round(percentage * 100) / 100);
    }
}
